package netgloo.models;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author chandan
 */
@Entity
@Table(name = "employee")
public class Employee implements Serializable {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@Column(name = "emp_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@NotNull
	private int empId;
	@Column(name = "emp_email")
	@NotNull
	private String email;

	// The user's email
	@Column(name = "emp_salary")
	@NotNull
	private int salary;

	@Column(name = "emp_city")
	@NotNull
	private String city;
	@Column(name = "emp_joining_year")
	@NotNull
	private String empJoinigYear;
	@Column(name = "emp_department")
	@NotNull
	private String empDepartment;
	@Column(name = "emp_designation")
	@NotNull
	private String empDesignation;

	public int getEmpId() {
		return empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getSalary() {
		return salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getEmpJoinigYear() {
		return empJoinigYear;
	}

	public void setEmpJoinigYear(String empJoinigYear) {
		this.empJoinigYear = empJoinigYear;
	}

	public String getEmpDepartment() {
		return empDepartment;
	}

	public void setEmpDepartment(String empDepartment) {
		this.empDepartment = empDepartment;
	}

	public String getEmpDesignation() {
		return empDesignation;
	}

	public void setEmpDesignation(String empDesignation) {
		this.empDesignation = empDesignation;
	}

}
